"""Configurable screen automation coordinates and timing."""

AUTO_TRADE_ENABLED = True
STEP_BUTTON_X = 350
STEP_BUTTON_Y = 980
BUY_BUTTON_X = 65
BUY_BUTTON_Y = 950
SELL_BUTTON_X = 130
SELL_BUTTON_Y = 950
PROCESS_TRADE_X = 310
PROCESS_TRADE_Y = 995
SLIDER_RIGHT_X = 160
SLIDER_RIGHT_Y = 990
STEP_DELAY_SECONDS = 0.75
ACTION_CLICK_DELAY_SECONDS = 0.2
TRADE_COOLDOWN_SECONDS = 1.0
SLIDER_DRAG_DURATION_SECONDS = 0.2
RUNTIME_CONFIG_PATH = "data/automation_config.json"
